# Generated by Django 4.1.2 on 2022-10-06 02:47

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.URLField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 6, 8, 17, 20, 542998))),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
