# Generated by Django 4.1.2 on 2022-10-06 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 8, 18, 4, 43669)),
        ),
    ]
