# Generated by Django 4.1.2 on 2022-10-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_followercount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followercount',
            old_name='user',
            new_name='username',
        ),
    ]
